### PR TITLE
Fix broken STAR-Russian link

### PR DESCRIPTION
**Pull request by bgins**
Removes a trailing slash to correct the link.

### CODE REVIEW

**Comment by andrew-silvernail** [comment]
I will do a build for this branch.

**Comment by bgins** [comment]
Oh right, I forgot about that. I just updated the PR with the compiled JavaScript.

**Comment by bgins** [comment]
Ah, you were building right while I was methinks :)

**Comment by andrew-silvernail** [comment]
> Ah, you were building right while I was methinks :)

No, was going to build later, but thank you for doing that!  Tested on Chrome, Firefox, and Safari, works great.

**Pull request merged**
