### PR TITLE
Student Profile Page Styling Enhancements

### PR DESCRIPTION
**Pull request by jdelamare**
Changes bring in order for flex items when the screen size shrinks below
768px. Also we've got a small change to remove `grid-colummn-template`
if the screensize shrinks smaller than "About this website
Acknowledgements". This wraps the text so there will be no horizontal
scrolling. That's basically the goal, no horiztonal scrolling.

Changes apply to login pages and student profile.

These changes improve styling on mobile devices.

- [ ] Check to see that navbar items are not cluttered on either the student or instructor page (since adding "Guide").
- [x] Buttons for research consent and show hints are now Material SVGs
- [ ] Links aren't cutoff (My Words PDF)
- [x] Adequate spacing around other links (performance report)
- [x] Grid item's order is preservered left-to-right top-to-bottom between mobile and desktop view
- [x] Performance report tabs "Completion and First Time Correct" span the width of the table when screensize no longer shinks the table (< 330px)

Changes take place mostly in ereader.css along with accompanying Elm files (Profile.elm for students)

### CODE REVIEW

**Comment by jdelamare** [comment]
https://user-images.githubusercontent.com/32110740/112521237-85b88400-8d59-11eb-96fb-96a590488a71.mov

**Comment by jdelamare** [comment]
Newly updated video showing desktop/mobile responsiveness.

**Comment by jdelamare** [comment]
Why does rebase always add commits?

**Review by bgins — APPROVED** [review]
Looks good overall. A couple of small fixes, and you can bring this in.

The "Update" username link is cut off on desktop and not visible on smaller devices. The spacing for the "Student Profile" title at the top of the page should be aligned with the corner of the border on medium/larger devices. The alignment looks good on mobile (when the left and right borders are flush with the device edges), but off on larger devices.

Screenshot showing those two:

update-cut-off

On mobile, it might look better to get rid of the border entirely. That way the alignment of the "Student Profile" title with the other items isn't visually broken.

remove-border

**Pull request merged**
